# ?? ??? ?? ??
spring:
  servlet:
    multipart:
      # ?? ?? ??(???? ??? ?? ???? ?? ??)
      location: C:\PJ
      # ?? ??? ?? ??
      max-file-size: 10MB
      # ?? ?? ?? ??
      max-request-size: 10MB