# datasource bean ? ?? ? DB ?? ??
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/menudb
    username: swcamp
    password: swcamp

# mybatis config ??
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ohgiraffers.transaction
  mapper-locations: mappers/**/*.xml